#? Config file for btop v.1.4.7

#* Name of a btop++/bpytop/bashtop formatted ".theme" file, "Default" and "TTY" for builtin themes.
#* Themes should be placed in "../share/btop/themes" relative to binary or "$HOME/.config/btop/themes"
color_theme = "/home/rexp10r/.config/btop/themes/catppuccin_mocha.theme"
