[colors.primary]
background = "#212B3C"
foreground = "#DCDDDF"

[colors.cursor]
cursor = "#DCDDDF"

[colors.normal]
black   = "#E6E7EA"
red     = "#8BC4D5"
green   = "#7598AA"
yellow  = "#D27A82"
blue    = "#798C97"
magenta = "#97747C"
cyan    = "#5D626B"
white   = "#3F5860"

[colors.bright]
black   = "#618995"
red     = "#8BC4D5"
green   = "#7598AA"
yellow  = "#D27A82"
blue    = "#798C97"
magenta = "#97747C"
cyan    = "#5D626B"
white   = "#BCD9E2"
