[colors.primary]
background = "#152234"
foreground = "#E4E6E8"

[colors.cursor]
cursor = "#E4E6E8"

[colors.normal]
black   = "#BABCC0"
red     = "#E3D5C1"
green   = "#7FD5FE"
yellow  = "#C496B1"
blue    = "#799786"
magenta = "#6B8BB7"
cyan    = "#A07499"
white   = "#666057"

[colors.bright]
black   = "#9F9587"
red     = "#E3D5C1"
green   = "#7FD5FE"
yellow  = "#C496B1"
blue    = "#729180"
magenta = "#6B8BB7"
cyan    = "#A07499"
white   = "#E9E2D8"
