[colors.primary]
background = "#17162B"
foreground = "#DEDEE0"

[colors.cursor]
cursor = "#DEDEE0"

[colors.normal]
black   = "#B1B0B4"
red     = "#ECDFEA"
green   = "#FEB588"
yellow  = "#DC96A2"
blue    = "#8791C3"
magenta = "#967985"
cyan    = "#52515D"
white   = "#6A6469"

[colors.bright]
black   = "#A59CA4"
red     = "#ECDFEA"
green   = "#FEB588"
yellow  = "#DC96A2"
blue    = "#8791C3"
magenta = "#967985"
cyan    = "#52515D"
white   = "#EDE7EC"
